// src/components/Application.vue
<template lang="pug">
div
  page-title(:title='pageTitle')
  h1.
    {{ application.name }}
    #[br]
    <small><small>
      #[a(v-if='application.isActive || application.linkInactive' :href='application.url') {{ application.url }}]
      #[span(v-if='!application.isActive && !application.linkInactive') {{ application.url }}]
      #[span(v-if='!application.isActive && !application.linkInactive && application.archiveUrl') &nbsp; &nbsp;]
      #[a(v-if='!application.isActive && !application.linkInactive && application.archiveUrl' :href='application.archiveUrl') <small>(Archive)</small>]
    </small></small>
  div.app-info
    aside: img(:src='imageLink')
    article.content
      p(v-for='(p, idx) in application.paragraphs' :key='idx' v-html='p')
      div(v-for='(act, idx) in application.activities' :key='"activity" + idx' :act='act')
        h3 {{ act.heading }}
        p(v-html='act.narrative')
      div(v-if='application.quotes.length > 0')
        h3 What They Say
        blockquote(v-for='(q, idx) in application.quotes' :key='"quote" + idx')
          p.quote(v-html='q.full')
          p.source
            != '&mdash; '
            strong.app-info-heading {{ q.name }}
            span(v-if='q.from') , {{ q.from }}
      p(v-for='(p, idx) in application.footnotes' :key='idx' v-html='p')
      p
        br
        router-link(:to="{ name: 'ApplicationList' }") &laquo; Back to All Solutions
</template>

<script lang="ts">
'use strict'

import Vue from 'vue'
import { Component, Prop } from 'vue-property-decorator'

import Data, { App } from '@/data'
import PageTitle from './PageTitle.vue'

@Component({ components: { PageTitle } })
export default class Application extends Vue {
  
  @Prop({ required: true })
  app!: string
  
  get application () {
    return Data.apps.find(app => app.id === this.app)
  }
  get imageLink () {
    return `/screenshots/${this.application!.id}.png`
  }
  get pageTitle () {
    return `${this.application!.name} « Solutions`
  }
}
</script>

<style lang="sass" scoped>
h1
  line-height: 1.6rem
.app-info
  display: flex
  flex-flow: row-reverse wrap
  justify-content: center
aside
  padding-left: 15px
aside img
  border: dotted 1px darkgray
  border-radius: 10px
blockquote
  border-left: solid 1px darkgray
  margin-left: 25px
  padding-left: 15px
.quote
  font-style: italic
.source
  text-align: right
  padding-right: 60px
</style>

// bit-badger-solutions/src/app/applications/application/application.component.ts
import { Component, OnInit, Input } from '@angular/core'
import { ActivatedRoute } from '@angular/router'

import { ApplicationService } from '../application.service'
import { App } from '../application.types'

@Component({
  selector: 'app-application',
  templateUrl: './application.component.html',
  styleUrls: ['./application.component.sass']
})
export class ApplicationComponent implements OnInit {

  /** The app we're displaying */
  application: App

  /** The page title based on this app */
  pageTitle: string

  /** Whether to link to the app's URL */
  linkToApp: boolean

  /** Whether to link to an archive URL */
  linkToArchive: boolean

  /** The link to the screenshot image */
  imageLink: string

  /** The alt text for the screenshot image */
  imageAlt: string

  constructor(
    private appService: ApplicationService,
    private route: ActivatedRoute
  ) { }

  ngOnInit() {
    const appId = this.route.snapshot.paramMap.get('appId')
    this.appService.getApp(appId)
      .subscribe(app => {
        this.application = app
        this.pageTitle = `${app.name} « Solutions`
        this.linkToApp = app.isActive || app.linkInactive
        this.linkToArchive = !app.isActive && !app.linkInactive && (app.archiveUrl > '')
        this.imageLink = `/assets/screenshots/${app.id}.png`
        this.imageAlt = `Screen shot for ${app.name}`
       })
  }

}

<app-page-title [title]="pageTitle"></app-page-title>
<div *ngIf="application">
  <h1>
    {{ application.name }}<br>
    <small><small>
      <a *ngIf="linkToApp" [href]="application.url">{{ application.url }}</a>
      <span *ngIf="!linkToApp">{{ application.url }}</span>
      <span *ngIf="linkToArchive">&nbsp; &nbsp;
        <a [href]="application.archiveUrl"><small>(Archive)</small></a>
      </span>
    </small></small>
  </h1>
  <div class="app-info">
    <aside><img [src]="imageLink" [alt]="imageAlt"></aside>
    <article class="content">
      <p *ngFor="let p of application.paragraphs" [innerHtml]="p"></p>
      <div *ngFor="let act of application.activities">
        <h3>{{ act.heading }}</h3>
        <p [innerHtml]="act.narrative"></p>
      </div>
      <div *ngIf="application.quotes.length > 0">
        <h3>What They Say</h3>
        <blockquote *ngFor="let q of application.quotes">
          <p class="quote" [innerHtml]="q.full"></p>
          <p class="source">
            &mdash; <strong class="app-info-heading">{{ q.name }}</strong>
            <span *ngIf="q.from">, {{ q.from }}</span>
          </p>
        </blockquote>
      </div>
      <p *ngFor="let p of application.footnotes" [innerHtml]="p"></p>
      <p><br><a routerLink="/solutions">&laquo; Back to All Solutions</a></p>
    </article>
  </div>
</div>
