// src/components/sidebar/SidebarApp.vue
<template lang="pug">
  div
    p.app-sidebar-name
      strong {{ app.name }}
      br
      span(v-if='!app.noAboutLink').
        #[router-link(:to="{ name: 'Application', params: { app: app.id } }" :title='aboutTitle') About] &bull; 
      a(:title='app.name' :href='app.url') Visit
    p.app-sidebar-description(v-html='app.frontPageText')
</template>

<script lang="ts">
'use strict'

import Vue from 'vue'
import { Component, Prop } from 'vue-property-decorator'

import { App } from '@/data'

@Component
export default class SidebarApp extends Vue {
  @Prop()
  app!: App

  /** The title attribute for the About link */
  get aboutTitle () {
    return `About ${this.app.name} | Bit Badger Solutions`
  }
}
</script>

// bit-badger-solutions/src/app/sidebar/sidebar-app/sidebar-app.component.ts
import { Component, OnInit, Input } from '@angular/core'

import { App } from 'src/app/applications/application.types'

@Component({
  selector: 'app-sidebar-app',
  templateUrl: './sidebar-app.component.html',
  styleUrls: ['./sidebar-app.component.sass']
})
export class SidebarAppComponent implements OnInit {

  @Input() app: App

  constructor() { }

  ngOnInit() { }
  
  /** The title attribute for the About link */
  get aboutTitle () {
    return `About ${this.app.name} | Bit Badger Solutions`
  }

}

<div>
  <p class="app-sidebar-name">
    <strong>{{ app.name }}</strong><br>
    <span *ngIf="!app.noAboutLink">
      <a routerLink="/solutions/{{ app.id }}" [title]="aboutTitle">About</a> &bull;
    </span>
    <a [routerLink]="app.url" [title]="app.name">Visit</a>
  </p>
  <p class="app-sidebar-description" [innerHtml]="app.frontPageText"></p>
</div>
