// src/components/about/LegacyData.vue
<template lang="pug">
article.content.auto
  page-title(title='Legacy Data Solutions')
  h1 Legacy Data Sharing
  p.
    Our background in mainframe applications gives us a knowledgeable perspective on retrieving information from
    older, &ldquo;legacy&rdquo; systems. This data can be migrated to a more modern relational or document database,
    where a web application can retrieve the information; in some cases, the data can even be exposed as a web service
    in place. These types of systems are often a great way for companies to expose their data to their customers,
    without having to move their day-to-day system from its current environment. While we currently have no active
    projects along these lines, our developers have done them in the past for other organizations; sadly, none can be
    linked publicly.
  p
    br
    router-link(to='/' title='Home') &laquo; Home
</template>

// bit-badger-solutions/src/app/pages/about/legacy-data.component.ts
import { Component, OnInit } from '@angular/core'

@Component({
  selector: 'app-legacy-data',
  templateUrl: './legacy-data.component.html'
})
export class LegacyDataComponent implements OnInit {

  constructor() { }

  ngOnInit() { }

}

<app-page-title title="Legacy Data Solutions"></app-page-title>
<article class="content auto">
  <h1>Legacy Data Sharing</h1>
  <p>
    Our background in mainframe applications gives us a knowledgeable perspective on retrieving information from
    older, &ldquo;legacy&rdquo; systems. This data can be migrated to a more modern relational or document database,
    where a web application can retrieve the information; in some cases, the data can even be exposed as a web service
    in place. These types of systems are often a great way for companies to expose their data to their customers,
    without having to move their day-to-day system from its current environment. While we currently have no active
    projects along these lines, our developers have done them in the past for other organizations; sadly, none can be
    linked publicly.
  </p>
  <p><br><a routerLink="/" title="Home">&laquo; Home</a></p>
</article>
