// bit-badger-solutions/src/app/applications/application-list-item/application-list-item.component.ts
import { Component, OnInit, Input } from '@angular/core'

import { App } from '../application.types'

@Component({
  selector: 'app-application-list-item',
  templateUrl: './application-list-item.component.html',
  styleUrls: ['./application-list-item.component.sass']
})
export class ApplicationListItemComponent implements OnInit {

  @Input() app: App

  constructor() { }

  ngOnInit() { }

}

<p>
  <span class="app-name" [innerHtml]="app.name"></span>&nbsp;~&nbsp;<a routerLink="/solutions/{{ app.id }}">About</a>
  <span *ngIf="app.isActive">&nbsp;~&nbsp;<a [href]="app.url">Visit</a></span>
  <span *ngIf="!app.isActive && app.archiveUrl">
    ~&nbsp;<a [href]="app.archiveUrl">Visit</a><em> (archive)</em>
  </span>
  <br>
  <span [innerHtml]="app.indexText"></span>
</p>

// src/components/ApplicationListItem.vue
<template>
  <p>
    <span class="app-name" v-html="app.name"></span> &nbsp;~&nbsp;
    <router-link :to="{ name: 'Application', params: { app: app.id } }">About</router-link>
    <span v-if="app.active"> &nbsp;~&nbsp; <a :href="app.url">Visit</a></span>
    <span v-if="!app.active && app.archiveUrl"> &nbsp;~&nbsp; <a :href="app.archiveUrl">Visit</a> <em>(archive)</em></span><br>
    <span v-html="app.indexText"></span>
  </p>
</template>

<script>
export default {
  name: 'application-list-item',
  props: ['app'],
  data: function () {
    return {}
  }
}
</script>

<style scoped>
.app-name {
  font-family: "Play", "Segoe UI", Ubuntu, "DejaVu Sans", "Liberation Sans", Arial, sans-serif;
  font-size: 1.1em;
  font-weight: bold;
  color: maroon;
}
</style>
