// src/components/ApplicationList.vue
<template lang="pug">
article.content.auto
  page-title(title='All Solutions')
  h1 All Solutions
  h2 Active Solutions
  application-list-item(v-for='app in current' :app='app' :key='app.id')
  h2 Past Solutions
  application-list-item(v-for='app in past' :app='app' :key='app.id')
</template>

<script>
import AppData from './AppData.vue'
import ApplicationListItem from './ApplicationListItem.vue'
import PageTitle from './PageTitle.vue'

export default {
  name: 'application-list',
  data: function () {
    return {
      current: AppData.apps.filter(app => app.active && !app.noAboutLink),
      past: AppData.apps.filter(app => !app.active && !app.noAboutLink)
    }
  },
  components: {
    ApplicationListItem,
    PageTitle
  }
}
</script>

// bit-badger-solutions/src/app/applications/application-list/application-list.component.ts
import { Component, OnInit } from '@angular/core'

import { ApplicationService } from '../application.service'
import { App } from '../application.types'

@Component({
  selector: 'app-application-list',
  templateUrl: './application-list.component.html'
})
export class ApplicationListComponent implements OnInit {

  current: App[]

  past: App[]

  constructor(private appService: ApplicationService) { }

  ngOnInit() {
    this.appService.getApps().subscribe(apps => {
      this.current = apps.filter(app => app.isActive && !app.noAboutLink)
      this.past = apps.filter(app => !app.isActive && !app.noAboutLink)
    })
  }

}

<app-page-title title="All Solutions"></app-page-title>
<article class="content auto">
  <h1>All Solutions</h1>
  <h2>Active Solutions</h2>
  <app-application-list-item *ngFor="let app of current" [app]="app"></app-application-list-item>
  <h2>Past Solutions</h2>
  <app-application-list-item *ngFor="let app of past" [app]="app"></app-application-list-item>
</article>
